### ISSUE TITLE
'chcp' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by MuneebAwan** [robots-from-jupyter/robotlab#39] opened 2019-09-12 05:18 UTC
When i run RobotLab it give me error "'chcp' is not recognized as an internal or external command"
![image](https://user-images.githubusercontent.com/8425825/64756020-b0136980-d546-11e9-922a-928e6daf4f3c.png)

**Comment by datakurre** [comment] 2019-09-12 07:57
@bollwyvl Might know what that is and how that could be missing.

What was your path to install RobotLab? I could try to reproduce.

I assume there is also a way to just start jupyterlab from the same environment.

**Comment by bollwyvl** [comment] 2019-09-13 01:19
Thanks for at least trying our little experiment out, @MuneebAwan... sorry you found a case we didn't test:
 
Not much of a windows guy, so i had to google what `chcp` does, and the problems of it not being found. Sounds like an [environment variable problem](https://stackoverflow.com/questions/8142058/chcp-is-not-recognized-as-an-internal-or-external-command-operable-program-or/8143664#8143664). If you (or some program on your behalf) has messed about with your `%PATH%` permanently (robotlab only messes about with it temporarily, we hope), you'll probably have some issues.

I'm betting somebody down in the robotlab stack (who knows, might be me!) is trying to generate some "pretty" output: `chcp` is some dark magic for changing terminal output, sometimes used to make ANSI/Unicode display.
 
If the shortcut is not working, can you try the more manual approach of:
- open a plain old [`cmd.exe` window](https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/)
- when the command prompt shows up
  - type `c:\users\mm\robotlab\scripts\activate c:\users\mm\robotlab`, press <kbd>enter</kbd>
  - type `robotlab`, press <kbd>enter</kbd>

That might get you going! We're long overdue on rebuilding this thing, though... perhaps if the stars align we can do some tidying up and get one out!

**Comment by bollwyvl** [comment] 2019-09-19 00:31
@MuneebAwan thanks again so much for trying RobotLab. We have a possible release candidate up and (barring any significant issues) should have a ~~alpha~~ ~~beta~~ ~~release~~ _something_ out soon.
 
In the meanwhile, there's this whole page of [troubleshooting](https://docs.anaconda.com/anaconda/user-guide/troubleshooting/) for Miniconda/Anaconda... since RobotLab is built _basically_ the same way, you can try and see if anything on there helps you out!

**Comment by bollwyvl** [comment] 2019-09-21 14:49
@MuneebAwan as promised, here's the updated release:
https://github.com/robots-from-jupyter/robotlab/releases/tag/v2019.9.0

Please take a spin and see if your problem persists: if it's still your `%PATH%` for system stuff maybe we can work through it!

**Comment by datakurre** [comment] 2019-12-10 08:39
And yet another release:
https://github.com/robots-from-jupyter/robotlab/releases/tag/v2019.12.0

After a few months without feedback and we being unable to reproduce this by ourselves, I close this now.

**Closed as completed by datakurre** 2019-12-10 08:39 UTC
Labels: 🐞 bug, 🔊 awaiting feedback

**Comment by RorisangSitoboli** [comment] 2022-03-23 17:06
In Windows open the command line and type:
'where chpc'
If it can't be located, you need to edit the Environment Variables. 
'Windows button' >> Type 'env' >> Select 'Edit the system variables' >> Select 'Advanced' >> Click 'Environment Variables' >> under User Variables scroll down to 'Path' and select/highlight it>> Click 'New' >> add the line 'C:\Windows\System32' >> Click 'OK' on all the prompts to make sure you close all the open tabs under 'System Environments'. Restart the PC. And you are all good.

This also works if 'cmd is not a recognised command, etc'.

**Comment by RorisangSitoboli** [comment] 2022-03-23 17:10
![env3](https://user-images.githubusercontent.com/26745924/159756635-eb33fdfd-f105-4bf7-934d-9a745a98ba05.png)
![env2](https://user-images.githubusercontent.com/26745924/159756640-625e574b-4549-40bd-84bd-7f57827063c2.png)
![env](https://user-images.githubusercontent.com/26745924/159756642-5111aa24-d737-478c-a201-7983d9407782.png)
