### ISSUE TITLE
Expose and highlight the robotkernel example notebooks

### ISSUE THREAD

**Issue by bollwyvl** [robots-from-jupyter/robotlab#3] opened 2018-11-22 15:55 UTC
The [example notebooks](https://github.com/datakurre/robotkernel/tree/master/examples) are already packaged as part of robotlab into `\var\www\robotkernel-examples`, but are hard to find.

There should also be an easy-to-use script to copy them (and any supporting stuff) into a given directory so that they are easy to find and try out.

The acceptance tests should then verify that they function properly. This will also uncover ermergent example dependencies (additional libraries, etc). At present, RESTInstance is the long pole...

**Comment by bollwyvl** [comment] 2018-11-24 04:39
Hm, it looks like the examples haven't been re-run in some time as it's not possible to get the same-ish pixels back at the per-output level. For example, the first `RESTinstance` example was saved with the first example printing out `en`, but it no longer does so. So I probably can't properly test these, as they have failing tests mixed in.

Still it was good practice to be able to learn more about some of the libraries in the examples, at any rate... it's pretty funny to be screenshot testing a couple levels deep.

![screenshot from 2018-11-23 23-35-25](https://user-images.githubusercontent.com/45380/48964571-7b630100-ef78-11e8-8552-cd58f73d4796.png)

(note, the highlighting is busted because this is a local dev version of robotlab, and i had just cleaned out the built app without putting the robotmode extension back in)

**Comment by datakurre** [comment] 2019-01-14 16:13
Should I do something here? I have rerun the examples once this year :-)

**Comment by bollwyvl** [comment] 2019-01-14 18:23
Probably nothing much is required in your end. I assume some of them
contain errors to be fixed by the reader, so it might be worth adding tags
to such cells. I think there's a canonical one that nbconvert recognizes...

**Comment by datakurre** [comment] 2019-01-14 18:54
Probably "raises-exception".

I'll ping here once I've added that and tried it with nbconvert myself.

**Comment by bollwyvl** [comment] 2019-01-14 20:26
Cheers. I might have to change the approach to getting it packaged. At
present, I'm just grabbing whatever's in the src tarball that goes with the
pip release. I'm not advocating for point releases per doc fix, though!

Once they are bit more predictable, we can test them, too, in the installer.

It's actually kinda cute: you can "library robotlab" and then "copy
robotkernel examples" or "copy robotkernel tutorial" and they just show up
in your local directory.

However, nothing doing for the next 8 hours: no wifi! Guess I'll draw some
things!

**Comment by datakurre** [comment] 2019-01-14 20:36
Safe travels!

**Comment by datakurre** [comment] 2019-01-15 14:38
I added "raises-exception"-tags, but it seems that at least nbconvert with support for that has not yet been released.

https://github.com/jupyter/nbconvert/issues/838

**Comment by datakurre** [comment] 2019-12-10 08:41
@bollwyvl Any new ideas, how we should bundle and present the examples? I will be working with the examples and tutorial for the next month, so now it is good time for ideas. :crossed_fingers:

**Comment by bollwyvl** [comment] 2019-12-10 13:17
The quick win is to just add launcher buttons in a custom extension that
copies the examples or the tutorial to the current directory, either by
abusing terminal or adding a small route to the server.

 I think a proper, pluggable, indexed documentation library is what I
really want. I was kinda of hoping I'd get to this on somebody else's
dime/time, but it hasn't happened yet.

Basically, you put _stuff_ (notebooks, html, PDF, docset) in _one of a few
places_ and the server indexes it, serves it (read only), remembers what
you read/bookmarked, and lets you copy it out, or run it in a temporary
directory. It's totally tractable, just a whole other thing to build, test,
and maintain.

**Comment by bollwyvl** [comment] 2019-12-16 15:09
Gah, had a saved draft with some follow-up. Anyhow, so I built this little
early 🎅🕎💈🎁:

https://github.com/deathbeds/jupyterlab-starters

Still working out the release (npm is in some weird state)... but the
binder works! I started it in the robotlab repo, but realized... It's
really hard to build new things there. And I need it for lots of stuff. But
it's 🤖 approved!

To add to robotlab would be one json/py file (and one py dep/recipe and...
kind of a few js deps because of the schema form stuff), and would give us
pretty good bang for our buck... We could even think about some one-off
templates.

Will PR when the release is working better!

**Comment by bollwyvl** [comment] 2019-12-16 16:34
Npm finally found my 📦, so I won't have to re-release. Yay!

**Comment by datakurre** [comment] 2019-12-16 18:01
😮

So, we may get this already for January workshop? (I’m updating the materials around the holidays.)

**Comment by bollwyvl** [comment] 2019-12-16 18:02
Yeah, like today 🕺🏽

**Comment by datakurre** [comment] 2019-12-16 18:03
🤯

**Comment by bollwyvl** [comment] 2019-12-17 03:21
Didn't work the first first time, will pick back up tomorrow...

**Comment by bollwyvl** [comment] 2019-12-17 15:34
Well, I have now tested that the extensions get installed with the right
version, and verified that the server extension is starting and serving a
request, but still not seeing the launchers...

**Comment by bollwyvl** [comment] 2019-12-18 04:01
found the issue: only stuff actually attached to `NotebookApp` is picked up by the cascading `conf.d` loader. working it out on [this pr](https://github.com/deathbeds/jupyterlab-starters/pull/6), should have another alpha out soon that will work for us here... indeed, i hacked through the changes needed by hacking directly on the as-installed-after-being-built-for-conda on #62. haven't looked into the windows fail yet...

**Comment by bollwyvl** [comment] 2020-01-15 01:34
Guess we can close this one now?  😴How'd the workshop go?

**Comment by datakurre** [comment] 2020-01-15 05:32
@bollwyvl Yes. We can close this. Starters worked for every participant. We had a couple of issues and I wonder if I should open placeholder issues for those later in hope that they will later gather comments from users having the same issues...

* MacOS SeleniumLibrary was unable to launch Firefox even when the machine did not have Firefox before the install; This might be the same issue you fixed for OpenCV or something related to MacOS sandboxing; I must try to reproduce this with a recent MacOS (I have old version at home, but have access to machine with new version at work).

* Couple of Windows PCs did not get the shortcut on their desktops (but robotlab worked well with Command Prompt + Scripts/activate + robotlab); I would guess something related to enterprise roaming profile setup.

* One Windows PC received SSL certificate validation errors from RobotLab while being able to browser web normally with web browser. I don't know if the Windows was completely up to date, or if a local firewall could cause such issues.

Generally we were able to repeat the last year's success and almost everyone had fully working setup in 20 minutes. And starters made trivial for everyone to find the materials. So, thank you!

**Closed as completed by datakurre** 2020-01-15 05:32 UTC
Labels: 🚀 enhancement, 🛶 upstreams, 😷 docs, 🧪 lab

**Comment by bollwyvl** [comment] 2020-01-15 14:53
> something related to MacOS sandboxing

Yeah, our test machine is old. Having some traces from real iron would be awesome. i never did get it working during conda build, which was a bummer.

>  Windows ... would guess something related to enterprise roaming profile setup.

i've run unto this on other things. I noticed `pyshortcuts` is under active development, and _may_ have fixed that in ensuing versions. Certainly worth an issue to explore, but devilish to test: there aren't enterprise-managed vms just hanging around to test against.

> Windows ... SSL certificate validation errors from RobotLab

no idea: firefox ships its own, and other things ship _their_ own, derived from firefox, and yet _other_ things use the system list. hard to tell!

**Comment by datakurre** [comment] 2020-01-16 06:56
@bollwyvl Good news on MacOS. I did meet the participant again during the conference days and now we tested "OpenCV.ipynb" (that had your customizations). That one did work, so we have hope.

I had one more issue: My SeleniumScreenshots calculate cropping wrong on some machines. Probably because of HiDPI. I guess, previously SeleniumLibrary did not capture HiDPI images so I only saw it now.
